#@follow_tag(registry-proxy.engineering.redhat.com/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23)
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23 AS builder
ENV DISTRIBUTION_DIR /go/src/github.com/docker/distribution
ARG GOOS=linux
ARG GOARCH=amd64
ARG GOARM=6
ARG VERSION
ARG REVISION
WORKDIR /workspace
COPY --chown=1001:0 . .
COPY --chown=1001:0 . /workspace/src/github.com/docker/distribution
WORKDIR /workspace/src/github.com/docker/distribution
ENV DISTRIBUTION_DIR /workspace/src/github.com/docker/distribution
USER root
RUN yum -y install make git file
USER 1001
ENV GOEXPERIMENT strictfipsruntime
ENV GO_BUILD_FLAGS=" -mod=readonly "
ENV BUILDTAGS=" include_oss include_gcs strictfipsruntime "
RUN CGO_ENABLED=1 make PREFIX=/go clean binaries

#@follow_tag(registry.redhat.io/ubi8/ubi-minimal)
FROM registry.redhat.io/ubi8/ubi-minimal:latest
RUN microdnf -y install ca-certificates httpd-tools && microdnf clean all
#RUN microdnf -y update && microdnf clean all
COPY --from=builder /workspace/src/github.com/docker/distribution/cmd/registry/config-dev.yml /etc/docker/registry/config.yml
COPY --from=builder /workspace/src/github.com/docker/distribution/bin/registry /bin/registry
VOLUME ["/var/lib/registry"]
EXPOSE 5000
USER 65534:65534
ENTRYPOINT ["registry"]
CMD ["serve", "/etc/docker/registry/config.yml"]

LABEL \
        com.redhat.component="openshift-migration-registry-container" \
        version="v1.8.7" \
        name="rhmtc/openshift-migration-registry-rhel8" \
        summary="Migration Toolkit for Containers Registry" \
        maintainer="Migration Team <ocp-migrate-team@redhat.com>" \
        License="Apache License 2.0" \
        io.k8s.display-name="Migration Toolkit for Containers" \
        io.openshift.tags="migration" \
        io.k8s.description="Migration Toolkit for Containers Registry" \
        io.openshift.build.commit.id="54066212c0d3291f5c285b11d6c9e7533723ba82" \
        io.openshift.build.source-location="https://github.com/migtools/distribution" \
        io.openshift.build.commit.url="https://github.com/migtools/distribution/commit/54066212c0d3291f5c285b11d6c9e7533723ba82"
